[workspace]
resolver = "2"
members = ["key-gen-ec", "rsa"]

[workspace.package]
name = "cryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
lambdaworks-math = "0.7.0"
